---
- hosts: localhost
  tasks:

  - name: Create an ssh keypair
    shell: ssh-keygen -b 2048 -t rsa -f $HOME/check -q -N ""
    args:
      creates: "{{ lookup('env', 'HOME')}}/check"

  - name: Setup EPEL
    yum: name=epel-release state=installed
  
  - name: Install dependency packages
    yum: name={{ item }} state=installed
    with_items:
    - nfs-utils
    - cifs-utils
    - libibverbs
    - python-pip
    - libxml2-devel
    - libxslt-devel
    - gcc
    - python-devel
    - fuse
    - fuse-libs

  - name: Setup the repo
    yum_repository:
      name: gluster_nightly
      description: The nightly repo for Gluster
      baseurl: http://artifacts.ci.centos.org/gluster/nightly/master/$releasever/$basearch
      gpgcheck: no
      repo_gpgcheck: no

  - name: Install gluster
    yum:
      name={{ item }} 
      state=installed
    with_items:
    - glusterfs-server
    - glusterfs-cli
    - glusterfs-debuginfo

  - name: start service
    service:
      name: glusterd
      state: started
      enabled: True

...
