---
- hosts: localhost
  tasks:
  - name: Create an ssh keypair
    shell: ssh-keygen -b 2048 -t rsa -q -N ""


  - name: Setup the repo
    yum_repository:
      name: gluster_nightly
      description: The nightly repo for Gluster
      baseurl: http://artifacts.ci.centos.org/gluster/nightly/master/$releasever/$basearch
      gpgcheck: no
      repo_gpgcheck: no

  - name: Install gluster
    yum: name={{ item }} state=installed
    with_items:
    - glusterfs-server
    - glusterfs-cli
    - glusterfs-debuginfo
...
